# Configuration file for running the ACASXu benchmark (all properties).
general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/acasxu  # Please clone the vnncomp2023 repo first as it contains the benchmark.
  csv_name: instances.csv
  enable_incomplete_verification: False
  loss_reduction_func: max
solver:
  batch_size: 1000  # Number of parallel domains to compute on GPU.
  bound_prop_method: crown
  beta-crown:
    iteration: 10  # Iterations for computing intermediate layer bounds.
  alpha-crown:
    iteration: 10
    share_alphas: True  # This produces slightly looser bounds, but faster.
bab:
  branching:
    method: naive  # Split on input space.
    input_split:
      enable: True
      enhanced_bound_prop_method: alpha-crown
      enhanced_bound_patience: 20
      enhanced_branching_method: sb
      sb_coeff_thresh: 0.01
attack:
  pgd_order: after
  pgd_restarts: 10000
