general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/vit
  csv_name: instances.csv
  loss_reduction_func: min
  sparse_alpha: false
  sparse_interm: false
  conv_mode: matrix
attack:
  pgd_order: skip
solver:
  batch_size: 32
  min_batch_size_ratio: 0.0
  auto_enlarge_batch_size: True
  alpha-crown:
    lr_alpha: 0.5
    iteration: 50
    max_time: 0.4
    disable_optimization: ['Exp']
  beta-crown:
    lr_alpha: 0.5
    lr_beta: 0.1
    iteration: 20
bab:
  pruning_in_iteration: False
  branching:
    method: nonlinear
    reduceop: min
