# Configuration file for running the oval21 benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/oval21  # Please update this path to point to the VNN-COMP 2022 repo
  csv_name: instances.csv
  conv_mode: matrix
solver:
  batch_size: 2048
  beta-crown:
    lr_beta: 0.01
  start_save_best: -1
  prune_after_crown: False
bab:
  pruning_in_iteration: False
  tree_traversal: breadth_first
  branching: 
    method: kfsb
    reduceop: max
    candidates: 10
  cut:
    enabled: True
    cplex_cuts: False
    bab_cut: True
    number_cuts: 500
    biccos:
      enabled: True
      max_infer_iter: 5
      constraint_strengthening: True
      recursively_strengthening: True
      multi_tree_branching:
        enabled: True
        keep_n_best_domains: 1
        k_splits: 200
        iterations: 1
attack:
  pgd_order: skip
